
DECLARE DS_DATETIME DATETIME DEFAULT NULL;
DECLARE DS_DATE DATETIME DEFAULT NULL;
SET (DS_DATETIME,DS_DATE) = ((SELECT CURRENT_DATETIME('Turkey')),(SELECT MAX(DT_UPDATE_DTTM) FROM `teknasyoncase.taxi_trips.F_TRX_TAXI_TRIPS_DROPOFF_LOCATION_CNT_D`));


-- Değişen kayıtları ods'ten gün kırılımında alır.

DROP TABLE IF EXISTS `teknasyoncase.taxi_trips.TEMP_DIST_DT_TRX_DATE_F_DROPOFF`;

CREATE TABLE `teknasyoncase.taxi_trips.TEMP_DIST_DT_TRX_DATE_F_DROPOFF` AS
SELECT DISTINCT DT_TRX_DATE
FROM `teknasyoncase.taxi_trips.TRX_TAXI_TRIPS`
WHERE 1 = 1
AND DT_UPDATE_DTTM >= DS_DATE;


-- Değişen kayıtları gün kırılımında siler.
DELETE `teknasyoncase.taxi_trips.F_TRX_TAXI_TRIPS_DROPOFF_LOCATION_CNT_D` d
WHERE EXISTS (SELECT 0
FROM `teknasyoncase.taxi_trips.TEMP_DIST_DT_TRX_DATE_F_DROPOFF` t
WHERE d.DT_TRX_DATE = t.DT_TRX_DATE);



-- Değişen kayıtları gün kırılımında insert eder.
INSERT INTO `teknasyoncase.taxi_trips.F_TRX_TAXI_TRIPS_DROPOFF_LOCATION_CNT_D`
SELECT DT_TRX_DATE,ID_DROPOFF_LOCATION,COUNT(ID_DROPOFF_LOCATION)MT_CNT_DROPOFF_LOCATION,DS_DATETIME AS DT_INSERT_DTTM, DS_DATETIME AS DT_UPDATE_DTTM
FROM `teknasyoncase.taxi_trips.TRX_TAXI_TRIPS` d
WHERE EXISTS (SELECT 0
FROM `teknasyoncase.taxi_trips.TEMP_DIST_DT_TRX_DATE_F_DROPOFF` t
WHERE d.DT_TRX_DATE = t.DT_TRX_DATE) 
GROUP BY DT_TRX_DATE,ID_DROPOFF_LOCATION;


DROP TABLE IF EXISTS `teknasyoncase.taxi_trips.TEMP_DIST_DT_TRX_DATE_F_DROPOFF`;


